### PR TITLE
Edit wrong coding ken of model and api Path

### PR DESCRIPTION
**Pull request by khalil-M**

### CODE REVIEW

**Review by ChristianSlanzi — CHANGES_REQUESTED** [review]
Good Job! Just some changes are necessary to the code. You created genreList, directorList, starList as [Dictionary<String, String>], essentially you converted a json structure in a dictionary and this is not efficient because you need to know the keys to access to the values. We want to create classes for these structures, then you have objects that you can play with, pass around and access to their properties through their names and not with keys.
Instead of dictionaries, you need to create a GenreDTO class, a DirectorDTO class and a StarDTO class. The classes should contain variables mapping what you have now inside the dictionaries.
For example, genreList prints out as 
GenreList = [["key": "Horror", "value": "Horror"], ["value": "Thriller", "key": "Thriller"]]
so it should be an array of GenreDTO aka
var genreList: [GenreDTO]
where you define GenreDTO, in a separate file, as
public struct GenreDTO: DTO {
    var key: String
    var value: String
    
    var description: String {
        return " .... "
    }
}

Look in the Xcode output window and try to find out what are the structures for directorList and starList to build up the DirectorDTO and StarDTO classes.

**Comment by khalil-M** [comment]
Hello Christian it's so nice to hear from you I appreciate your help and
advice
I should do it ;)

Le dim. 1 août 2021 à 13:43, Christian Slanzi ***@***.***> a
écrit :

**Comment by khalil-M** [comment]
Hello Christian
I successfully get the expected result :)
but i can't create a pull request

Le dim. 1 août 2021 à 14:00, khalil mhelheli ***@***.***> a
écrit :

**Comment by ChristianSlanzi** [comment]
That's correct. Since there was already a pull request opened by you, every changes you commit and push in the meanwhile they get added to the same request, till I won't close and merge it.

Still a little change then it's done. Could you please change in NewMovieDataDetail the line
`DirectorList = \(starList)`
in
`starList = \(starList)`
, then the print of the description will be correct.

**Comment by ChristianSlanzi** [comment]
Well done! I'm going to merge the PR.

**Pull request merged**
